server:
  port: 9526

spring:
  cloud:
    gateway:
      routes:
        - id: path_route_01
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/**
  application:
    name: springcloud-Gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: Gateway6666
    prefer-ip-address: true