server:
  port: 80
spring:
  application:
    name: cloud-feign-order

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000